# Generated by Django 3.1.3 on 2020-11-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('portrait', 'portrait'), ('sketch', 'sketch'), ('landscape', 'landscape'), ('nature', 'nature'), ('b&w', 'b&w'), ('wildlife', 'wildlife')], default='portrait', max_length=10)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='pics')),
                ('tag', models.ManyToManyField(to='images.Tag')),
            ],
            options={
                'verbose_name': 'image object',
                'verbose_name_plural': 'image objects',
                'db_table': 'image_object',
            },
        ),
    ]
