# Generated by Django 3.1.2 on 2020-11-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20201201_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageobject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
